// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ZCHXRadar.proto

#ifndef PROTOBUF_ZCHXRadar_2eproto__INCLUDED
#define PROTOBUF_ZCHXRadar_2eproto__INCLUDED

#include <string>
#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace zhichenhaixin {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ZCHXRadar_2eproto();
void protobuf_AssignDesc_ZCHXRadar_2eproto();
void protobuf_ShutdownFile_ZCHXRadar_2eproto();

class RadarHistoryTrack;
class RadarHistoryTracks;
class TrackPoint;
class RadarSurfaceTrack;
class VideoFrame;

enum MSGTYP {
  MSGTYP_UNDEFINED = 0,
  TARGET_REPORT = 1,
  START_OF_UPDATE_CYCLE = 2,
  PERIODIC_STATUS = 3,
  EVENT_TRIGGERED_STATUS = 4
};
bool MSGTYP_IsValid(int value);
const MSGTYP MSGTYP_MIN = MSGTYP_UNDEFINED;
const MSGTYP MSGTYP_MAX = EVENT_TRIGGERED_STATUS;
const int MSGTYP_ARRAYSIZE = MSGTYP_MAX + 1;

const ::google::protobuf::EnumDescriptor* MSGTYP_descriptor();
inline const ::std::string& MSGTYP_Name(MSGTYP value) {
  return ::google::protobuf::internal::NameOfEnum(
    MSGTYP_descriptor(), value);
}
inline bool MSGTYP_Parse(
    const ::std::string& name, MSGTYP* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MSGTYP>(
    MSGTYP_descriptor(), name, value);
}
enum CNF {
  CONFIRMED_TRACK = 0,
  TENTATIVE_TRACK = 1,
  UNKNOWN_TRACK = 2
};
bool CNF_IsValid(int value);
const CNF CNF_MIN = CONFIRMED_TRACK;
const CNF CNF_MAX = UNKNOWN_TRACK;
const int CNF_ARRAYSIZE = CNF_MAX + 1;

const ::google::protobuf::EnumDescriptor* CNF_descriptor();
inline const ::std::string& CNF_Name(CNF value) {
  return ::google::protobuf::internal::NameOfEnum(
    CNF_descriptor(), value);
}
inline bool CNF_Parse(
    const ::std::string& name, CNF* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CNF>(
    CNF_descriptor(), name, value);
}
enum CST {
  CST_UNDEFINED = 0,
  PREDICTABLE_EXTRAPOLATION_DUE_PERIOD = 1,
  PREDICTABLE_EXTRAPOLATION_IN_AREA = 2,
  EXTRAPOLATION_DUE_UNPREDICTABLE_DETECTION = 3
};
bool CST_IsValid(int value);
const CST CST_MIN = CST_UNDEFINED;
const CST CST_MAX = EXTRAPOLATION_DUE_UNPREDICTABLE_DETECTION;
const int CST_ARRAYSIZE = CST_MAX + 1;

const ::google::protobuf::EnumDescriptor* CST_descriptor();
inline const ::std::string& CST_Name(CST value) {
  return ::google::protobuf::internal::NameOfEnum(
    CST_descriptor(), value);
}
inline bool CST_Parse(
    const ::std::string& name, CST* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CST>(
    CST_descriptor(), name, value);
}
enum STH {
  MEASURED_POSITION = 0,
  SMOOTHED_POSITION = 1
};
bool STH_IsValid(int value);
const STH STH_MIN = MEASURED_POSITION;
const STH STH_MAX = SMOOTHED_POSITION;
const int STH_ARRAYSIZE = STH_MAX + 1;

const ::google::protobuf::EnumDescriptor* STH_descriptor();
inline const ::std::string& STH_Name(STH value) {
  return ::google::protobuf::internal::NameOfEnum(
    STH_descriptor(), value);
}
inline bool STH_Parse(
    const ::std::string& name, STH* value) {
  return ::google::protobuf::internal::ParseNamedEnum<STH>(
    STH_descriptor(), name, value);
}
enum RES {
  MONOBIT_RESOLUTION = 1,
  LOW_RESOLUTION = 2,
  MEDIUM_RESOLUTION = 3,
  HIGH_RESOLUTION = 4,
  VERY_HIGH_RESOLUTION = 5,
  ULTRA_HIGH_RESOLUTION = 6
};
bool RES_IsValid(int value);
const RES RES_MIN = MONOBIT_RESOLUTION;
const RES RES_MAX = ULTRA_HIGH_RESOLUTION;
const int RES_ARRAYSIZE = RES_MAX + 1;

const ::google::protobuf::EnumDescriptor* RES_descriptor();
inline const ::std::string& RES_Name(RES value) {
  return ::google::protobuf::internal::NameOfEnum(
    RES_descriptor(), value);
}
inline bool RES_Parse(
    const ::std::string& name, RES* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RES>(
    RES_descriptor(), name, value);
}
// ===================================================================

class  RadarHistoryTrack : public ::google::protobuf::Message {
 public:
  RadarHistoryTrack();
  virtual ~RadarHistoryTrack();

  RadarHistoryTrack(const RadarHistoryTrack& from);

  inline RadarHistoryTrack& operator=(const RadarHistoryTrack& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RadarHistoryTrack& default_instance();

  void Swap(RadarHistoryTrack* other);

  // implements Message ----------------------------------------------

  RadarHistoryTrack* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RadarHistoryTrack& from);
  void MergeFrom(const RadarHistoryTrack& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 trackNumber = 1;
  inline bool has_tracknumber() const;
  inline void clear_tracknumber();
  static const int kTrackNumberFieldNumber = 1;
  inline ::google::protobuf::int64 tracknumber() const;
  inline void set_tracknumber(::google::protobuf::int64 value);

  // required double wgs84PosLat = 2;
  inline bool has_wgs84poslat() const;
  inline void clear_wgs84poslat();
  static const int kWgs84PosLatFieldNumber = 2;
  inline double wgs84poslat() const;
  inline void set_wgs84poslat(double value);

  // required double wgs84PosLong = 3;
  inline bool has_wgs84poslong() const;
  inline void clear_wgs84poslong();
  static const int kWgs84PosLongFieldNumber = 3;
  inline double wgs84poslong() const;
  inline void set_wgs84poslong(double value);

  // required float timeOfDay = 4;
  inline bool has_timeofday() const;
  inline void clear_timeofday();
  static const int kTimeOfDayFieldNumber = 4;
  inline float timeofday() const;
  inline void set_timeofday(float value);

  // optional .com.zhichenhaixin.proto.CNF trackType = 5;
  inline bool has_tracktype() const;
  inline void clear_tracktype();
  static const int kTrackTypeFieldNumber = 5;
  inline ::com::zhichenhaixin::proto::CNF tracktype() const;
  inline void set_tracktype(::com::zhichenhaixin::proto::CNF value);

  // optional .com.zhichenhaixin.proto.CST extrapolation = 7;
  inline bool has_extrapolation() const;
  inline void clear_extrapolation();
  static const int kExtrapolationFieldNumber = 7;
  inline ::com::zhichenhaixin::proto::CST extrapolation() const;
  inline void set_extrapolation(::com::zhichenhaixin::proto::CST value);

  // optional .com.zhichenhaixin.proto.STH trackPositionCode = 8;
  inline bool has_trackpositioncode() const;
  inline void clear_trackpositioncode();
  static const int kTrackPositionCodeFieldNumber = 8;
  inline ::com::zhichenhaixin::proto::STH trackpositioncode() const;
  inline void set_trackpositioncode(::com::zhichenhaixin::proto::STH value);

  // required double cog = 9;
  inline bool has_cog() const;
  inline void clear_cog();
  static const int kCogFieldNumber = 9;
  inline double cog() const;
  inline void set_cog(double value);

  // required double sog = 10;
  inline bool has_sog() const;
  inline void clear_sog();
  static const int kSogFieldNumber = 10;
  inline double sog() const;
  inline void set_sog(double value);

  // required uint64 UTC = 11;
  inline bool has_utc() const;
  inline void clear_utc();
  static const int kUTCFieldNumber = 11;
  inline ::google::protobuf::uint64 utc() const;
  inline void set_utc(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:com.zhichenhaixin.proto.RadarHistoryTrack)
 private:
  inline void set_has_tracknumber();
  inline void clear_has_tracknumber();
  inline void set_has_wgs84poslat();
  inline void clear_has_wgs84poslat();
  inline void set_has_wgs84poslong();
  inline void clear_has_wgs84poslong();
  inline void set_has_timeofday();
  inline void clear_has_timeofday();
  inline void set_has_tracktype();
  inline void clear_has_tracktype();
  inline void set_has_extrapolation();
  inline void clear_has_extrapolation();
  inline void set_has_trackpositioncode();
  inline void clear_has_trackpositioncode();
  inline void set_has_cog();
  inline void clear_has_cog();
  inline void set_has_sog();
  inline void clear_has_sog();
  inline void set_has_utc();
  inline void clear_has_utc();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 tracknumber_;
  double wgs84poslat_;
  double wgs84poslong_;
  float timeofday_;
  int tracktype_;
  int extrapolation_;
  int trackpositioncode_;
  double cog_;
  double sog_;
  ::google::protobuf::uint64 utc_;
  friend void  protobuf_AddDesc_ZCHXRadar_2eproto();
  friend void protobuf_AssignDesc_ZCHXRadar_2eproto();
  friend void protobuf_ShutdownFile_ZCHXRadar_2eproto();

  void InitAsDefaultInstance();
  static RadarHistoryTrack* default_instance_;
};
// -------------------------------------------------------------------

class  RadarHistoryTracks : public ::google::protobuf::Message {
 public:
  RadarHistoryTracks();
  virtual ~RadarHistoryTracks();

  RadarHistoryTracks(const RadarHistoryTracks& from);

  inline RadarHistoryTracks& operator=(const RadarHistoryTracks& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RadarHistoryTracks& default_instance();

  void Swap(RadarHistoryTracks* other);

  // implements Message ----------------------------------------------

  RadarHistoryTracks* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RadarHistoryTracks& from);
  void MergeFrom(const RadarHistoryTracks& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .com.zhichenhaixin.proto.RadarHistoryTrack track = 1;
  inline int track_size() const;
  inline void clear_track();
  static const int kTrackFieldNumber = 1;
  inline const ::com::zhichenhaixin::proto::RadarHistoryTrack& track(int index) const;
  inline ::com::zhichenhaixin::proto::RadarHistoryTrack* mutable_track(int index);
  inline ::com::zhichenhaixin::proto::RadarHistoryTrack* add_track();
  inline const ::google::protobuf::RepeatedPtrField< ::com::zhichenhaixin::proto::RadarHistoryTrack >&
      track() const;
  inline ::google::protobuf::RepeatedPtrField< ::com::zhichenhaixin::proto::RadarHistoryTrack >*
      mutable_track();

  // @@protoc_insertion_point(class_scope:com.zhichenhaixin.proto.RadarHistoryTracks)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::com::zhichenhaixin::proto::RadarHistoryTrack > track_;
  friend void  protobuf_AddDesc_ZCHXRadar_2eproto();
  friend void protobuf_AssignDesc_ZCHXRadar_2eproto();
  friend void protobuf_ShutdownFile_ZCHXRadar_2eproto();

  void InitAsDefaultInstance();
  static RadarHistoryTracks* default_instance_;
};
// -------------------------------------------------------------------

class  TrackPoint : public ::google::protobuf::Message {
 public:
  TrackPoint();
  virtual ~TrackPoint();

  TrackPoint(const TrackPoint& from);

  inline TrackPoint& operator=(const TrackPoint& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TrackPoint& default_instance();

  void Swap(TrackPoint* other);

  // implements Message ----------------------------------------------

  TrackPoint* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TrackPoint& from);
  void MergeFrom(const TrackPoint& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 systemAreaCode = 1;
  inline bool has_systemareacode() const;
  inline void clear_systemareacode();
  static const int kSystemAreaCodeFieldNumber = 1;
  inline ::google::protobuf::int32 systemareacode() const;
  inline void set_systemareacode(::google::protobuf::int32 value);

  // required int32 systemIdentificationCode = 2;
  inline bool has_systemidentificationcode() const;
  inline void clear_systemidentificationcode();
  static const int kSystemIdentificationCodeFieldNumber = 2;
  inline ::google::protobuf::int32 systemidentificationcode() const;
  inline void set_systemidentificationcode(::google::protobuf::int32 value);

  // required .com.zhichenhaixin.proto.MSGTYP messageType = 3;
  inline bool has_messagetype() const;
  inline void clear_messagetype();
  static const int kMessageTypeFieldNumber = 3;
  inline ::com::zhichenhaixin::proto::MSGTYP messagetype() const;
  inline void set_messagetype(::com::zhichenhaixin::proto::MSGTYP value);

  // required uint32 trackNumber = 4;
  inline bool has_tracknumber() const;
  inline void clear_tracknumber();
  static const int kTrackNumberFieldNumber = 4;
  inline ::google::protobuf::uint32 tracknumber() const;
  inline void set_tracknumber(::google::protobuf::uint32 value);

  // required float cartesianPosX = 5;
  inline bool has_cartesianposx() const;
  inline void clear_cartesianposx();
  static const int kCartesianPosXFieldNumber = 5;
  inline float cartesianposx() const;
  inline void set_cartesianposx(float value);

  // required float cartesianPosY = 6;
  inline bool has_cartesianposy() const;
  inline void clear_cartesianposy();
  static const int kCartesianPosYFieldNumber = 6;
  inline float cartesianposy() const;
  inline void set_cartesianposy(float value);

  // required double wgs84PosLat = 7;
  inline bool has_wgs84poslat() const;
  inline void clear_wgs84poslat();
  static const int kWgs84PosLatFieldNumber = 7;
  inline double wgs84poslat() const;
  inline void set_wgs84poslat(double value);

  // required double wgs84PosLong = 8;
  inline bool has_wgs84poslong() const;
  inline void clear_wgs84poslong();
  static const int kWgs84PosLongFieldNumber = 8;
  inline double wgs84poslong() const;
  inline void set_wgs84poslong(double value);

  // required float timeOfDay = 9;
  inline bool has_timeofday() const;
  inline void clear_timeofday();
  static const int kTimeOfDayFieldNumber = 9;
  inline float timeofday() const;
  inline void set_timeofday(float value);

  // optional .com.zhichenhaixin.proto.CNF trackType = 10;
  inline bool has_tracktype() const;
  inline void clear_tracktype();
  static const int kTrackTypeFieldNumber = 10;
  inline ::com::zhichenhaixin::proto::CNF tracktype() const;
  inline void set_tracktype(::com::zhichenhaixin::proto::CNF value);

  // optional bool trackLastReport = 11;
  inline bool has_tracklastreport() const;
  inline void clear_tracklastreport();
  static const int kTrackLastReportFieldNumber = 11;
  inline bool tracklastreport() const;
  inline void set_tracklastreport(bool value);

  // optional .com.zhichenhaixin.proto.CST extrapolation = 12;
  inline bool has_extrapolation() const;
  inline void clear_extrapolation();
  static const int kExtrapolationFieldNumber = 12;
  inline ::com::zhichenhaixin::proto::CST extrapolation() const;
  inline void set_extrapolation(::com::zhichenhaixin::proto::CST value);

  // optional .com.zhichenhaixin.proto.STH trackPositionCode = 13;
  inline bool has_trackpositioncode() const;
  inline void clear_trackpositioncode();
  static const int kTrackPositionCodeFieldNumber = 13;
  inline ::com::zhichenhaixin::proto::STH trackpositioncode() const;
  inline void set_trackpositioncode(::com::zhichenhaixin::proto::STH value);

  // optional float sigmaX = 14;
  inline bool has_sigmax() const;
  inline void clear_sigmax();
  static const int kSigmaXFieldNumber = 14;
  inline float sigmax() const;
  inline void set_sigmax(float value);

  // optional float sigmaY = 15;
  inline bool has_sigmay() const;
  inline void clear_sigmay();
  static const int kSigmaYFieldNumber = 15;
  inline float sigmay() const;
  inline void set_sigmay(float value);

  // optional float sigmaXY = 16;
  inline bool has_sigmaxy() const;
  inline void clear_sigmaxy();
  static const int kSigmaXYFieldNumber = 16;
  inline float sigmaxy() const;
  inline void set_sigmaxy(float value);

  // optional float ampOfPriPlot = 17;
  inline bool has_ampofpriplot() const;
  inline void clear_ampofpriplot();
  static const int kAmpOfPriPlotFieldNumber = 17;
  inline float ampofpriplot() const;
  inline void set_ampofpriplot(float value);

  // required double cartesianTrkVel_vx = 18;
  inline bool has_cartesiantrkvel_vx() const;
  inline void clear_cartesiantrkvel_vx();
  static const int kCartesianTrkVelVxFieldNumber = 18;
  inline double cartesiantrkvel_vx() const;
  inline void set_cartesiantrkvel_vx(double value);

  // required double cartesianTrkVel_vy = 19;
  inline bool has_cartesiantrkvel_vy() const;
  inline void clear_cartesiantrkvel_vy();
  static const int kCartesianTrkVelVyFieldNumber = 19;
  inline double cartesiantrkvel_vy() const;
  inline void set_cartesiantrkvel_vy(double value);

  // required double cog = 20;
  inline bool has_cog() const;
  inline void clear_cog();
  static const int kCogFieldNumber = 20;
  inline double cog() const;
  inline void set_cog(double value);

  // required double sog = 21;
  inline bool has_sog() const;
  inline void clear_sog();
  static const int kSogFieldNumber = 21;
  inline double sog() const;
  inline void set_sog(double value);

  // optional int32 fleetNumber = 22;
  inline bool has_fleetnumber() const;
  inline void clear_fleetnumber();
  static const int kFleetNumberFieldNumber = 22;
  inline ::google::protobuf::int32 fleetnumber() const;
  inline void set_fleetnumber(::google::protobuf::int32 value);

  // optional int32 status = 23;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 23;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);

  // optional string lonType = 24;
  inline bool has_lontype() const;
  inline void clear_lontype();
  static const int kLonTypeFieldNumber = 24;
  inline const ::std::string& lontype() const;
  inline void set_lontype(const ::std::string& value);
  inline void set_lontype(const char* value);
  inline void set_lontype(const char* value, size_t size);
  inline ::std::string* mutable_lontype();
  inline ::std::string* release_lontype();
  inline void set_allocated_lontype(::std::string* lontype);

  // optional string latType = 25;
  inline bool has_lattype() const;
  inline void clear_lattype();
  static const int kLatTypeFieldNumber = 25;
  inline const ::std::string& lattype() const;
  inline void set_lattype(const ::std::string& value);
  inline void set_lattype(const char* value);
  inline void set_lattype(const char* value, size_t size);
  inline ::std::string* mutable_lattype();
  inline ::std::string* release_lattype();
  inline void set_allocated_lattype(::std::string* lattype);

  // optional int32 type = 26;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 26;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // optional string aisid = 27;
  inline bool has_aisid() const;
  inline void clear_aisid();
  static const int kAisidFieldNumber = 27;
  inline const ::std::string& aisid() const;
  inline void set_aisid(const ::std::string& value);
  inline void set_aisid(const char* value);
  inline void set_aisid(const char* value, size_t size);
  inline ::std::string* mutable_aisid();
  inline ::std::string* release_aisid();
  inline void set_allocated_aisid(::std::string* aisid);

  // optional .com.zhichenhaixin.proto.RadarHistoryTracks tracks = 28;
  inline bool has_tracks() const;
  inline void clear_tracks();
  static const int kTracksFieldNumber = 28;
  inline const ::com::zhichenhaixin::proto::RadarHistoryTracks& tracks() const;
  inline ::com::zhichenhaixin::proto::RadarHistoryTracks* mutable_tracks();
  inline ::com::zhichenhaixin::proto::RadarHistoryTracks* release_tracks();
  inline void set_allocated_tracks(::com::zhichenhaixin::proto::RadarHistoryTracks* tracks);

  // optional int32 diameter = 29;
  inline bool has_diameter() const;
  inline void clear_diameter();
  static const int kDiameterFieldNumber = 29;
  inline ::google::protobuf::int32 diameter() const;
  inline void set_diameter(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.zhichenhaixin.proto.TrackPoint)
 private:
  inline void set_has_systemareacode();
  inline void clear_has_systemareacode();
  inline void set_has_systemidentificationcode();
  inline void clear_has_systemidentificationcode();
  inline void set_has_messagetype();
  inline void clear_has_messagetype();
  inline void set_has_tracknumber();
  inline void clear_has_tracknumber();
  inline void set_has_cartesianposx();
  inline void clear_has_cartesianposx();
  inline void set_has_cartesianposy();
  inline void clear_has_cartesianposy();
  inline void set_has_wgs84poslat();
  inline void clear_has_wgs84poslat();
  inline void set_has_wgs84poslong();
  inline void clear_has_wgs84poslong();
  inline void set_has_timeofday();
  inline void clear_has_timeofday();
  inline void set_has_tracktype();
  inline void clear_has_tracktype();
  inline void set_has_tracklastreport();
  inline void clear_has_tracklastreport();
  inline void set_has_extrapolation();
  inline void clear_has_extrapolation();
  inline void set_has_trackpositioncode();
  inline void clear_has_trackpositioncode();
  inline void set_has_sigmax();
  inline void clear_has_sigmax();
  inline void set_has_sigmay();
  inline void clear_has_sigmay();
  inline void set_has_sigmaxy();
  inline void clear_has_sigmaxy();
  inline void set_has_ampofpriplot();
  inline void clear_has_ampofpriplot();
  inline void set_has_cartesiantrkvel_vx();
  inline void clear_has_cartesiantrkvel_vx();
  inline void set_has_cartesiantrkvel_vy();
  inline void clear_has_cartesiantrkvel_vy();
  inline void set_has_cog();
  inline void clear_has_cog();
  inline void set_has_sog();
  inline void clear_has_sog();
  inline void set_has_fleetnumber();
  inline void clear_has_fleetnumber();
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_lontype();
  inline void clear_has_lontype();
  inline void set_has_lattype();
  inline void clear_has_lattype();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_aisid();
  inline void clear_has_aisid();
  inline void set_has_tracks();
  inline void clear_has_tracks();
  inline void set_has_diameter();
  inline void clear_has_diameter();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 systemareacode_;
  ::google::protobuf::int32 systemidentificationcode_;
  int messagetype_;
  ::google::protobuf::uint32 tracknumber_;
  float cartesianposx_;
  float cartesianposy_;
  double wgs84poslat_;
  double wgs84poslong_;
  float timeofday_;
  int tracktype_;
  bool tracklastreport_;
  int extrapolation_;
  int trackpositioncode_;
  float sigmax_;
  float sigmay_;
  float sigmaxy_;
  double cartesiantrkvel_vx_;
  double cartesiantrkvel_vy_;
  float ampofpriplot_;
  ::google::protobuf::int32 fleetnumber_;
  double cog_;
  double sog_;
  ::std::string* lontype_;
  ::google::protobuf::int32 status_;
  ::google::protobuf::int32 type_;
  ::std::string* lattype_;
  ::std::string* aisid_;
  ::com::zhichenhaixin::proto::RadarHistoryTracks* tracks_;
  ::google::protobuf::int32 diameter_;
  friend void  protobuf_AddDesc_ZCHXRadar_2eproto();
  friend void protobuf_AssignDesc_ZCHXRadar_2eproto();
  friend void protobuf_ShutdownFile_ZCHXRadar_2eproto();

  void InitAsDefaultInstance();
  static TrackPoint* default_instance_;
};
// -------------------------------------------------------------------

class  RadarSurfaceTrack : public ::google::protobuf::Message {
 public:
  RadarSurfaceTrack();
  virtual ~RadarSurfaceTrack();

  RadarSurfaceTrack(const RadarSurfaceTrack& from);

  inline RadarSurfaceTrack& operator=(const RadarSurfaceTrack& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RadarSurfaceTrack& default_instance();

  void Swap(RadarSurfaceTrack* other);

  // implements Message ----------------------------------------------

  RadarSurfaceTrack* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RadarSurfaceTrack& from);
  void MergeFrom(const RadarSurfaceTrack& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 flag = 1;
  inline bool has_flag() const;
  inline void clear_flag();
  static const int kFlagFieldNumber = 1;
  inline ::google::protobuf::int32 flag() const;
  inline void set_flag(::google::protobuf::int32 value);

  // required string sourceId = 2;
  inline bool has_sourceid() const;
  inline void clear_sourceid();
  static const int kSourceIdFieldNumber = 2;
  inline const ::std::string& sourceid() const;
  inline void set_sourceid(const ::std::string& value);
  inline void set_sourceid(const char* value);
  inline void set_sourceid(const char* value, size_t size);
  inline ::std::string* mutable_sourceid();
  inline ::std::string* release_sourceid();
  inline void set_allocated_sourceid(::std::string* sourceid);

  // required uint64 UTC = 3;
  inline bool has_utc() const;
  inline void clear_utc();
  static const int kUTCFieldNumber = 3;
  inline ::google::protobuf::uint64 utc() const;
  inline void set_utc(::google::protobuf::uint64 value);

  // required int32 length = 4;
  inline bool has_length() const;
  inline void clear_length();
  static const int kLengthFieldNumber = 4;
  inline ::google::protobuf::int32 length() const;
  inline void set_length(::google::protobuf::int32 value);

  // repeated .com.zhichenhaixin.proto.TrackPoint trackPoints = 5;
  inline int trackpoints_size() const;
  inline void clear_trackpoints();
  static const int kTrackPointsFieldNumber = 5;
  inline const ::com::zhichenhaixin::proto::TrackPoint& trackpoints(int index) const;
  inline ::com::zhichenhaixin::proto::TrackPoint* mutable_trackpoints(int index);
  inline ::com::zhichenhaixin::proto::TrackPoint* add_trackpoints();
  inline const ::google::protobuf::RepeatedPtrField< ::com::zhichenhaixin::proto::TrackPoint >&
      trackpoints() const;
  inline ::google::protobuf::RepeatedPtrField< ::com::zhichenhaixin::proto::TrackPoint >*
      mutable_trackpoints();

  // @@protoc_insertion_point(class_scope:com.zhichenhaixin.proto.RadarSurfaceTrack)
 private:
  inline void set_has_flag();
  inline void clear_has_flag();
  inline void set_has_sourceid();
  inline void clear_has_sourceid();
  inline void set_has_utc();
  inline void clear_has_utc();
  inline void set_has_length();
  inline void clear_has_length();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* sourceid_;
  ::google::protobuf::int32 flag_;
  ::google::protobuf::int32 length_;
  ::google::protobuf::uint64 utc_;
  ::google::protobuf::RepeatedPtrField< ::com::zhichenhaixin::proto::TrackPoint > trackpoints_;
  friend void  protobuf_AddDesc_ZCHXRadar_2eproto();
  friend void protobuf_AssignDesc_ZCHXRadar_2eproto();
  friend void protobuf_ShutdownFile_ZCHXRadar_2eproto();

  void InitAsDefaultInstance();
  static RadarSurfaceTrack* default_instance_;
};
// -------------------------------------------------------------------

class  VideoFrame : public ::google::protobuf::Message {
 public:
  VideoFrame();
  virtual ~VideoFrame();

  VideoFrame(const VideoFrame& from);

  inline VideoFrame& operator=(const VideoFrame& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const VideoFrame& default_instance();

  void Swap(VideoFrame* other);

  // implements Message ----------------------------------------------

  VideoFrame* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const VideoFrame& from);
  void MergeFrom(const VideoFrame& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 systemAreaCode = 1;
  inline bool has_systemareacode() const;
  inline void clear_systemareacode();
  static const int kSystemAreaCodeFieldNumber = 1;
  inline ::google::protobuf::int32 systemareacode() const;
  inline void set_systemareacode(::google::protobuf::int32 value);

  // required int32 systemIdentificationCode = 2;
  inline bool has_systemidentificationcode() const;
  inline void clear_systemidentificationcode();
  static const int kSystemIdentificationCodeFieldNumber = 2;
  inline ::google::protobuf::int32 systemidentificationcode() const;
  inline void set_systemidentificationcode(::google::protobuf::int32 value);

  // required int32 msgIndex = 3;
  inline bool has_msgindex() const;
  inline void clear_msgindex();
  static const int kMsgIndexFieldNumber = 3;
  inline ::google::protobuf::int32 msgindex() const;
  inline void set_msgindex(::google::protobuf::int32 value);

  // required uint32 azimuth = 4;
  inline bool has_azimuth() const;
  inline void clear_azimuth();
  static const int kAzimuthFieldNumber = 4;
  inline ::google::protobuf::uint32 azimuth() const;
  inline void set_azimuth(::google::protobuf::uint32 value);

  // optional uint32 heading = 5;
  inline bool has_heading() const;
  inline void clear_heading();
  static const int kHeadingFieldNumber = 5;
  inline ::google::protobuf::uint32 heading() const;
  inline void set_heading(::google::protobuf::uint32 value);

  // required double startRange = 6;
  inline bool has_startrange() const;
  inline void clear_startrange();
  static const int kStartRangeFieldNumber = 6;
  inline double startrange() const;
  inline void set_startrange(double value);

  // required double rangeFactor = 7;
  inline bool has_rangefactor() const;
  inline void clear_rangefactor();
  static const int kRangeFactorFieldNumber = 7;
  inline double rangefactor() const;
  inline void set_rangefactor(double value);

  // required .com.zhichenhaixin.proto.RES bitResolution = 8;
  inline bool has_bitresolution() const;
  inline void clear_bitresolution();
  static const int kBitResolutionFieldNumber = 8;
  inline ::com::zhichenhaixin::proto::RES bitresolution() const;
  inline void set_bitresolution(::com::zhichenhaixin::proto::RES value);

  // required int32 timeOfDay = 9;
  inline bool has_timeofday() const;
  inline void clear_timeofday();
  static const int kTimeOfDayFieldNumber = 9;
  inline ::google::protobuf::int32 timeofday() const;
  inline void set_timeofday(::google::protobuf::int32 value);

  // repeated int32 amplitude = 10;
  inline int amplitude_size() const;
  inline void clear_amplitude();
  static const int kAmplitudeFieldNumber = 10;
  inline ::google::protobuf::int32 amplitude(int index) const;
  inline void set_amplitude(int index, ::google::protobuf::int32 value);
  inline void add_amplitude(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      amplitude() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_amplitude();

  // @@protoc_insertion_point(class_scope:com.zhichenhaixin.proto.VideoFrame)
 private:
  inline void set_has_systemareacode();
  inline void clear_has_systemareacode();
  inline void set_has_systemidentificationcode();
  inline void clear_has_systemidentificationcode();
  inline void set_has_msgindex();
  inline void clear_has_msgindex();
  inline void set_has_azimuth();
  inline void clear_has_azimuth();
  inline void set_has_heading();
  inline void clear_has_heading();
  inline void set_has_startrange();
  inline void clear_has_startrange();
  inline void set_has_rangefactor();
  inline void clear_has_rangefactor();
  inline void set_has_bitresolution();
  inline void clear_has_bitresolution();
  inline void set_has_timeofday();
  inline void clear_has_timeofday();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 systemareacode_;
  ::google::protobuf::int32 systemidentificationcode_;
  ::google::protobuf::int32 msgindex_;
  ::google::protobuf::uint32 azimuth_;
  double startrange_;
  ::google::protobuf::uint32 heading_;
  int bitresolution_;
  double rangefactor_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > amplitude_;
  ::google::protobuf::int32 timeofday_;
  friend void  protobuf_AddDesc_ZCHXRadar_2eproto();
  friend void protobuf_AssignDesc_ZCHXRadar_2eproto();
  friend void protobuf_ShutdownFile_ZCHXRadar_2eproto();

  void InitAsDefaultInstance();
  static VideoFrame* default_instance_;
};
// ===================================================================


// ===================================================================

// RadarHistoryTrack

// required int64 trackNumber = 1;
inline bool RadarHistoryTrack::has_tracknumber() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RadarHistoryTrack::set_has_tracknumber() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RadarHistoryTrack::clear_has_tracknumber() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RadarHistoryTrack::clear_tracknumber() {
  tracknumber_ = GOOGLE_LONGLONG(0);
  clear_has_tracknumber();
}
inline ::google::protobuf::int64 RadarHistoryTrack::tracknumber() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.RadarHistoryTrack.trackNumber)
  return tracknumber_;
}
inline void RadarHistoryTrack::set_tracknumber(::google::protobuf::int64 value) {
  set_has_tracknumber();
  tracknumber_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.RadarHistoryTrack.trackNumber)
}

// required double wgs84PosLat = 2;
inline bool RadarHistoryTrack::has_wgs84poslat() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RadarHistoryTrack::set_has_wgs84poslat() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RadarHistoryTrack::clear_has_wgs84poslat() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RadarHistoryTrack::clear_wgs84poslat() {
  wgs84poslat_ = 0;
  clear_has_wgs84poslat();
}
inline double RadarHistoryTrack::wgs84poslat() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.RadarHistoryTrack.wgs84PosLat)
  return wgs84poslat_;
}
inline void RadarHistoryTrack::set_wgs84poslat(double value) {
  set_has_wgs84poslat();
  wgs84poslat_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.RadarHistoryTrack.wgs84PosLat)
}

// required double wgs84PosLong = 3;
inline bool RadarHistoryTrack::has_wgs84poslong() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RadarHistoryTrack::set_has_wgs84poslong() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RadarHistoryTrack::clear_has_wgs84poslong() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RadarHistoryTrack::clear_wgs84poslong() {
  wgs84poslong_ = 0;
  clear_has_wgs84poslong();
}
inline double RadarHistoryTrack::wgs84poslong() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.RadarHistoryTrack.wgs84PosLong)
  return wgs84poslong_;
}
inline void RadarHistoryTrack::set_wgs84poslong(double value) {
  set_has_wgs84poslong();
  wgs84poslong_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.RadarHistoryTrack.wgs84PosLong)
}

// required float timeOfDay = 4;
inline bool RadarHistoryTrack::has_timeofday() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RadarHistoryTrack::set_has_timeofday() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RadarHistoryTrack::clear_has_timeofday() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RadarHistoryTrack::clear_timeofday() {
  timeofday_ = 0;
  clear_has_timeofday();
}
inline float RadarHistoryTrack::timeofday() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.RadarHistoryTrack.timeOfDay)
  return timeofday_;
}
inline void RadarHistoryTrack::set_timeofday(float value) {
  set_has_timeofday();
  timeofday_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.RadarHistoryTrack.timeOfDay)
}

// optional .com.zhichenhaixin.proto.CNF trackType = 5;
inline bool RadarHistoryTrack::has_tracktype() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RadarHistoryTrack::set_has_tracktype() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RadarHistoryTrack::clear_has_tracktype() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RadarHistoryTrack::clear_tracktype() {
  tracktype_ = 0;
  clear_has_tracktype();
}
inline ::com::zhichenhaixin::proto::CNF RadarHistoryTrack::tracktype() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.RadarHistoryTrack.trackType)
  return static_cast< ::com::zhichenhaixin::proto::CNF >(tracktype_);
}
inline void RadarHistoryTrack::set_tracktype(::com::zhichenhaixin::proto::CNF value) {
  assert(::com::zhichenhaixin::proto::CNF_IsValid(value));
  set_has_tracktype();
  tracktype_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.RadarHistoryTrack.trackType)
}

// optional .com.zhichenhaixin.proto.CST extrapolation = 7;
inline bool RadarHistoryTrack::has_extrapolation() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RadarHistoryTrack::set_has_extrapolation() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RadarHistoryTrack::clear_has_extrapolation() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RadarHistoryTrack::clear_extrapolation() {
  extrapolation_ = 0;
  clear_has_extrapolation();
}
inline ::com::zhichenhaixin::proto::CST RadarHistoryTrack::extrapolation() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.RadarHistoryTrack.extrapolation)
  return static_cast< ::com::zhichenhaixin::proto::CST >(extrapolation_);
}
inline void RadarHistoryTrack::set_extrapolation(::com::zhichenhaixin::proto::CST value) {
  assert(::com::zhichenhaixin::proto::CST_IsValid(value));
  set_has_extrapolation();
  extrapolation_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.RadarHistoryTrack.extrapolation)
}

// optional .com.zhichenhaixin.proto.STH trackPositionCode = 8;
inline bool RadarHistoryTrack::has_trackpositioncode() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RadarHistoryTrack::set_has_trackpositioncode() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RadarHistoryTrack::clear_has_trackpositioncode() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RadarHistoryTrack::clear_trackpositioncode() {
  trackpositioncode_ = 0;
  clear_has_trackpositioncode();
}
inline ::com::zhichenhaixin::proto::STH RadarHistoryTrack::trackpositioncode() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.RadarHistoryTrack.trackPositionCode)
  return static_cast< ::com::zhichenhaixin::proto::STH >(trackpositioncode_);
}
inline void RadarHistoryTrack::set_trackpositioncode(::com::zhichenhaixin::proto::STH value) {
  assert(::com::zhichenhaixin::proto::STH_IsValid(value));
  set_has_trackpositioncode();
  trackpositioncode_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.RadarHistoryTrack.trackPositionCode)
}

// required double cog = 9;
inline bool RadarHistoryTrack::has_cog() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RadarHistoryTrack::set_has_cog() {
  _has_bits_[0] |= 0x00000080u;
}
inline void RadarHistoryTrack::clear_has_cog() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void RadarHistoryTrack::clear_cog() {
  cog_ = 0;
  clear_has_cog();
}
inline double RadarHistoryTrack::cog() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.RadarHistoryTrack.cog)
  return cog_;
}
inline void RadarHistoryTrack::set_cog(double value) {
  set_has_cog();
  cog_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.RadarHistoryTrack.cog)
}

// required double sog = 10;
inline bool RadarHistoryTrack::has_sog() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void RadarHistoryTrack::set_has_sog() {
  _has_bits_[0] |= 0x00000100u;
}
inline void RadarHistoryTrack::clear_has_sog() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void RadarHistoryTrack::clear_sog() {
  sog_ = 0;
  clear_has_sog();
}
inline double RadarHistoryTrack::sog() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.RadarHistoryTrack.sog)
  return sog_;
}
inline void RadarHistoryTrack::set_sog(double value) {
  set_has_sog();
  sog_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.RadarHistoryTrack.sog)
}

// required uint64 UTC = 11;
inline bool RadarHistoryTrack::has_utc() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void RadarHistoryTrack::set_has_utc() {
  _has_bits_[0] |= 0x00000200u;
}
inline void RadarHistoryTrack::clear_has_utc() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void RadarHistoryTrack::clear_utc() {
  utc_ = GOOGLE_ULONGLONG(0);
  clear_has_utc();
}
inline ::google::protobuf::uint64 RadarHistoryTrack::utc() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.RadarHistoryTrack.UTC)
  return utc_;
}
inline void RadarHistoryTrack::set_utc(::google::protobuf::uint64 value) {
  set_has_utc();
  utc_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.RadarHistoryTrack.UTC)
}

// -------------------------------------------------------------------

// RadarHistoryTracks

// repeated .com.zhichenhaixin.proto.RadarHistoryTrack track = 1;
inline int RadarHistoryTracks::track_size() const {
  return track_.size();
}
inline void RadarHistoryTracks::clear_track() {
  track_.Clear();
}
inline const ::com::zhichenhaixin::proto::RadarHistoryTrack& RadarHistoryTracks::track(int index) const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.RadarHistoryTracks.track)
  return track_.Get(index);
}
inline ::com::zhichenhaixin::proto::RadarHistoryTrack* RadarHistoryTracks::mutable_track(int index) {
  // @@protoc_insertion_point(field_mutable:com.zhichenhaixin.proto.RadarHistoryTracks.track)
  return track_.Mutable(index);
}
inline ::com::zhichenhaixin::proto::RadarHistoryTrack* RadarHistoryTracks::add_track() {
  // @@protoc_insertion_point(field_add:com.zhichenhaixin.proto.RadarHistoryTracks.track)
  return track_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::zhichenhaixin::proto::RadarHistoryTrack >&
RadarHistoryTracks::track() const {
  // @@protoc_insertion_point(field_list:com.zhichenhaixin.proto.RadarHistoryTracks.track)
  return track_;
}
inline ::google::protobuf::RepeatedPtrField< ::com::zhichenhaixin::proto::RadarHistoryTrack >*
RadarHistoryTracks::mutable_track() {
  // @@protoc_insertion_point(field_mutable_list:com.zhichenhaixin.proto.RadarHistoryTracks.track)
  return &track_;
}

// -------------------------------------------------------------------

// TrackPoint

// required int32 systemAreaCode = 1;
inline bool TrackPoint::has_systemareacode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TrackPoint::set_has_systemareacode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TrackPoint::clear_has_systemareacode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TrackPoint::clear_systemareacode() {
  systemareacode_ = 0;
  clear_has_systemareacode();
}
inline ::google::protobuf::int32 TrackPoint::systemareacode() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.systemAreaCode)
  return systemareacode_;
}
inline void TrackPoint::set_systemareacode(::google::protobuf::int32 value) {
  set_has_systemareacode();
  systemareacode_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.systemAreaCode)
}

// required int32 systemIdentificationCode = 2;
inline bool TrackPoint::has_systemidentificationcode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TrackPoint::set_has_systemidentificationcode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TrackPoint::clear_has_systemidentificationcode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TrackPoint::clear_systemidentificationcode() {
  systemidentificationcode_ = 0;
  clear_has_systemidentificationcode();
}
inline ::google::protobuf::int32 TrackPoint::systemidentificationcode() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.systemIdentificationCode)
  return systemidentificationcode_;
}
inline void TrackPoint::set_systemidentificationcode(::google::protobuf::int32 value) {
  set_has_systemidentificationcode();
  systemidentificationcode_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.systemIdentificationCode)
}

// required .com.zhichenhaixin.proto.MSGTYP messageType = 3;
inline bool TrackPoint::has_messagetype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TrackPoint::set_has_messagetype() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TrackPoint::clear_has_messagetype() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TrackPoint::clear_messagetype() {
  messagetype_ = 0;
  clear_has_messagetype();
}
inline ::com::zhichenhaixin::proto::MSGTYP TrackPoint::messagetype() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.messageType)
  return static_cast< ::com::zhichenhaixin::proto::MSGTYP >(messagetype_);
}
inline void TrackPoint::set_messagetype(::com::zhichenhaixin::proto::MSGTYP value) {
  assert(::com::zhichenhaixin::proto::MSGTYP_IsValid(value));
  set_has_messagetype();
  messagetype_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.messageType)
}

// required uint32 trackNumber = 4;
inline bool TrackPoint::has_tracknumber() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TrackPoint::set_has_tracknumber() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TrackPoint::clear_has_tracknumber() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TrackPoint::clear_tracknumber() {
  tracknumber_ = 0u;
  clear_has_tracknumber();
}
inline ::google::protobuf::uint32 TrackPoint::tracknumber() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.trackNumber)
  return tracknumber_;
}
inline void TrackPoint::set_tracknumber(::google::protobuf::uint32 value) {
  set_has_tracknumber();
  tracknumber_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.trackNumber)
}

// required float cartesianPosX = 5;
inline bool TrackPoint::has_cartesianposx() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void TrackPoint::set_has_cartesianposx() {
  _has_bits_[0] |= 0x00000010u;
}
inline void TrackPoint::clear_has_cartesianposx() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void TrackPoint::clear_cartesianposx() {
  cartesianposx_ = 0;
  clear_has_cartesianposx();
}
inline float TrackPoint::cartesianposx() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.cartesianPosX)
  return cartesianposx_;
}
inline void TrackPoint::set_cartesianposx(float value) {
  set_has_cartesianposx();
  cartesianposx_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.cartesianPosX)
}

// required float cartesianPosY = 6;
inline bool TrackPoint::has_cartesianposy() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void TrackPoint::set_has_cartesianposy() {
  _has_bits_[0] |= 0x00000020u;
}
inline void TrackPoint::clear_has_cartesianposy() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void TrackPoint::clear_cartesianposy() {
  cartesianposy_ = 0;
  clear_has_cartesianposy();
}
inline float TrackPoint::cartesianposy() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.cartesianPosY)
  return cartesianposy_;
}
inline void TrackPoint::set_cartesianposy(float value) {
  set_has_cartesianposy();
  cartesianposy_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.cartesianPosY)
}

// required double wgs84PosLat = 7;
inline bool TrackPoint::has_wgs84poslat() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void TrackPoint::set_has_wgs84poslat() {
  _has_bits_[0] |= 0x00000040u;
}
inline void TrackPoint::clear_has_wgs84poslat() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void TrackPoint::clear_wgs84poslat() {
  wgs84poslat_ = 0;
  clear_has_wgs84poslat();
}
inline double TrackPoint::wgs84poslat() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.wgs84PosLat)
  return wgs84poslat_;
}
inline void TrackPoint::set_wgs84poslat(double value) {
  set_has_wgs84poslat();
  wgs84poslat_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.wgs84PosLat)
}

// required double wgs84PosLong = 8;
inline bool TrackPoint::has_wgs84poslong() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void TrackPoint::set_has_wgs84poslong() {
  _has_bits_[0] |= 0x00000080u;
}
inline void TrackPoint::clear_has_wgs84poslong() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void TrackPoint::clear_wgs84poslong() {
  wgs84poslong_ = 0;
  clear_has_wgs84poslong();
}
inline double TrackPoint::wgs84poslong() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.wgs84PosLong)
  return wgs84poslong_;
}
inline void TrackPoint::set_wgs84poslong(double value) {
  set_has_wgs84poslong();
  wgs84poslong_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.wgs84PosLong)
}

// required float timeOfDay = 9;
inline bool TrackPoint::has_timeofday() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void TrackPoint::set_has_timeofday() {
  _has_bits_[0] |= 0x00000100u;
}
inline void TrackPoint::clear_has_timeofday() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void TrackPoint::clear_timeofday() {
  timeofday_ = 0;
  clear_has_timeofday();
}
inline float TrackPoint::timeofday() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.timeOfDay)
  return timeofday_;
}
inline void TrackPoint::set_timeofday(float value) {
  set_has_timeofday();
  timeofday_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.timeOfDay)
}

// optional .com.zhichenhaixin.proto.CNF trackType = 10;
inline bool TrackPoint::has_tracktype() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void TrackPoint::set_has_tracktype() {
  _has_bits_[0] |= 0x00000200u;
}
inline void TrackPoint::clear_has_tracktype() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void TrackPoint::clear_tracktype() {
  tracktype_ = 0;
  clear_has_tracktype();
}
inline ::com::zhichenhaixin::proto::CNF TrackPoint::tracktype() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.trackType)
  return static_cast< ::com::zhichenhaixin::proto::CNF >(tracktype_);
}
inline void TrackPoint::set_tracktype(::com::zhichenhaixin::proto::CNF value) {
  assert(::com::zhichenhaixin::proto::CNF_IsValid(value));
  set_has_tracktype();
  tracktype_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.trackType)
}

// optional bool trackLastReport = 11;
inline bool TrackPoint::has_tracklastreport() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void TrackPoint::set_has_tracklastreport() {
  _has_bits_[0] |= 0x00000400u;
}
inline void TrackPoint::clear_has_tracklastreport() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void TrackPoint::clear_tracklastreport() {
  tracklastreport_ = false;
  clear_has_tracklastreport();
}
inline bool TrackPoint::tracklastreport() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.trackLastReport)
  return tracklastreport_;
}
inline void TrackPoint::set_tracklastreport(bool value) {
  set_has_tracklastreport();
  tracklastreport_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.trackLastReport)
}

// optional .com.zhichenhaixin.proto.CST extrapolation = 12;
inline bool TrackPoint::has_extrapolation() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void TrackPoint::set_has_extrapolation() {
  _has_bits_[0] |= 0x00000800u;
}
inline void TrackPoint::clear_has_extrapolation() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void TrackPoint::clear_extrapolation() {
  extrapolation_ = 0;
  clear_has_extrapolation();
}
inline ::com::zhichenhaixin::proto::CST TrackPoint::extrapolation() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.extrapolation)
  return static_cast< ::com::zhichenhaixin::proto::CST >(extrapolation_);
}
inline void TrackPoint::set_extrapolation(::com::zhichenhaixin::proto::CST value) {
  assert(::com::zhichenhaixin::proto::CST_IsValid(value));
  set_has_extrapolation();
  extrapolation_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.extrapolation)
}

// optional .com.zhichenhaixin.proto.STH trackPositionCode = 13;
inline bool TrackPoint::has_trackpositioncode() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void TrackPoint::set_has_trackpositioncode() {
  _has_bits_[0] |= 0x00001000u;
}
inline void TrackPoint::clear_has_trackpositioncode() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void TrackPoint::clear_trackpositioncode() {
  trackpositioncode_ = 0;
  clear_has_trackpositioncode();
}
inline ::com::zhichenhaixin::proto::STH TrackPoint::trackpositioncode() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.trackPositionCode)
  return static_cast< ::com::zhichenhaixin::proto::STH >(trackpositioncode_);
}
inline void TrackPoint::set_trackpositioncode(::com::zhichenhaixin::proto::STH value) {
  assert(::com::zhichenhaixin::proto::STH_IsValid(value));
  set_has_trackpositioncode();
  trackpositioncode_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.trackPositionCode)
}

// optional float sigmaX = 14;
inline bool TrackPoint::has_sigmax() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void TrackPoint::set_has_sigmax() {
  _has_bits_[0] |= 0x00002000u;
}
inline void TrackPoint::clear_has_sigmax() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void TrackPoint::clear_sigmax() {
  sigmax_ = 0;
  clear_has_sigmax();
}
inline float TrackPoint::sigmax() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.sigmaX)
  return sigmax_;
}
inline void TrackPoint::set_sigmax(float value) {
  set_has_sigmax();
  sigmax_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.sigmaX)
}

// optional float sigmaY = 15;
inline bool TrackPoint::has_sigmay() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void TrackPoint::set_has_sigmay() {
  _has_bits_[0] |= 0x00004000u;
}
inline void TrackPoint::clear_has_sigmay() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void TrackPoint::clear_sigmay() {
  sigmay_ = 0;
  clear_has_sigmay();
}
inline float TrackPoint::sigmay() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.sigmaY)
  return sigmay_;
}
inline void TrackPoint::set_sigmay(float value) {
  set_has_sigmay();
  sigmay_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.sigmaY)
}

// optional float sigmaXY = 16;
inline bool TrackPoint::has_sigmaxy() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void TrackPoint::set_has_sigmaxy() {
  _has_bits_[0] |= 0x00008000u;
}
inline void TrackPoint::clear_has_sigmaxy() {
  _has_bits_[0] &= ~0x00008000u;
}
inline void TrackPoint::clear_sigmaxy() {
  sigmaxy_ = 0;
  clear_has_sigmaxy();
}
inline float TrackPoint::sigmaxy() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.sigmaXY)
  return sigmaxy_;
}
inline void TrackPoint::set_sigmaxy(float value) {
  set_has_sigmaxy();
  sigmaxy_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.sigmaXY)
}

// optional float ampOfPriPlot = 17;
inline bool TrackPoint::has_ampofpriplot() const {
  return (_has_bits_[0] & 0x00010000u) != 0;
}
inline void TrackPoint::set_has_ampofpriplot() {
  _has_bits_[0] |= 0x00010000u;
}
inline void TrackPoint::clear_has_ampofpriplot() {
  _has_bits_[0] &= ~0x00010000u;
}
inline void TrackPoint::clear_ampofpriplot() {
  ampofpriplot_ = 0;
  clear_has_ampofpriplot();
}
inline float TrackPoint::ampofpriplot() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.ampOfPriPlot)
  return ampofpriplot_;
}
inline void TrackPoint::set_ampofpriplot(float value) {
  set_has_ampofpriplot();
  ampofpriplot_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.ampOfPriPlot)
}

// required double cartesianTrkVel_vx = 18;
inline bool TrackPoint::has_cartesiantrkvel_vx() const {
  return (_has_bits_[0] & 0x00020000u) != 0;
}
inline void TrackPoint::set_has_cartesiantrkvel_vx() {
  _has_bits_[0] |= 0x00020000u;
}
inline void TrackPoint::clear_has_cartesiantrkvel_vx() {
  _has_bits_[0] &= ~0x00020000u;
}
inline void TrackPoint::clear_cartesiantrkvel_vx() {
  cartesiantrkvel_vx_ = 0;
  clear_has_cartesiantrkvel_vx();
}
inline double TrackPoint::cartesiantrkvel_vx() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.cartesianTrkVel_vx)
  return cartesiantrkvel_vx_;
}
inline void TrackPoint::set_cartesiantrkvel_vx(double value) {
  set_has_cartesiantrkvel_vx();
  cartesiantrkvel_vx_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.cartesianTrkVel_vx)
}

// required double cartesianTrkVel_vy = 19;
inline bool TrackPoint::has_cartesiantrkvel_vy() const {
  return (_has_bits_[0] & 0x00040000u) != 0;
}
inline void TrackPoint::set_has_cartesiantrkvel_vy() {
  _has_bits_[0] |= 0x00040000u;
}
inline void TrackPoint::clear_has_cartesiantrkvel_vy() {
  _has_bits_[0] &= ~0x00040000u;
}
inline void TrackPoint::clear_cartesiantrkvel_vy() {
  cartesiantrkvel_vy_ = 0;
  clear_has_cartesiantrkvel_vy();
}
inline double TrackPoint::cartesiantrkvel_vy() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.cartesianTrkVel_vy)
  return cartesiantrkvel_vy_;
}
inline void TrackPoint::set_cartesiantrkvel_vy(double value) {
  set_has_cartesiantrkvel_vy();
  cartesiantrkvel_vy_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.cartesianTrkVel_vy)
}

// required double cog = 20;
inline bool TrackPoint::has_cog() const {
  return (_has_bits_[0] & 0x00080000u) != 0;
}
inline void TrackPoint::set_has_cog() {
  _has_bits_[0] |= 0x00080000u;
}
inline void TrackPoint::clear_has_cog() {
  _has_bits_[0] &= ~0x00080000u;
}
inline void TrackPoint::clear_cog() {
  cog_ = 0;
  clear_has_cog();
}
inline double TrackPoint::cog() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.cog)
  return cog_;
}
inline void TrackPoint::set_cog(double value) {
  set_has_cog();
  cog_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.cog)
}

// required double sog = 21;
inline bool TrackPoint::has_sog() const {
  return (_has_bits_[0] & 0x00100000u) != 0;
}
inline void TrackPoint::set_has_sog() {
  _has_bits_[0] |= 0x00100000u;
}
inline void TrackPoint::clear_has_sog() {
  _has_bits_[0] &= ~0x00100000u;
}
inline void TrackPoint::clear_sog() {
  sog_ = 0;
  clear_has_sog();
}
inline double TrackPoint::sog() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.sog)
  return sog_;
}
inline void TrackPoint::set_sog(double value) {
  set_has_sog();
  sog_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.sog)
}

// optional int32 fleetNumber = 22;
inline bool TrackPoint::has_fleetnumber() const {
  return (_has_bits_[0] & 0x00200000u) != 0;
}
inline void TrackPoint::set_has_fleetnumber() {
  _has_bits_[0] |= 0x00200000u;
}
inline void TrackPoint::clear_has_fleetnumber() {
  _has_bits_[0] &= ~0x00200000u;
}
inline void TrackPoint::clear_fleetnumber() {
  fleetnumber_ = 0;
  clear_has_fleetnumber();
}
inline ::google::protobuf::int32 TrackPoint::fleetnumber() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.fleetNumber)
  return fleetnumber_;
}
inline void TrackPoint::set_fleetnumber(::google::protobuf::int32 value) {
  set_has_fleetnumber();
  fleetnumber_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.fleetNumber)
}

// optional int32 status = 23;
inline bool TrackPoint::has_status() const {
  return (_has_bits_[0] & 0x00400000u) != 0;
}
inline void TrackPoint::set_has_status() {
  _has_bits_[0] |= 0x00400000u;
}
inline void TrackPoint::clear_has_status() {
  _has_bits_[0] &= ~0x00400000u;
}
inline void TrackPoint::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 TrackPoint::status() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.status)
  return status_;
}
inline void TrackPoint::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.status)
}

// optional string lonType = 24;
inline bool TrackPoint::has_lontype() const {
  return (_has_bits_[0] & 0x00800000u) != 0;
}
inline void TrackPoint::set_has_lontype() {
  _has_bits_[0] |= 0x00800000u;
}
inline void TrackPoint::clear_has_lontype() {
  _has_bits_[0] &= ~0x00800000u;
}
inline void TrackPoint::clear_lontype() {
  if (lontype_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lontype_->clear();
  }
  clear_has_lontype();
}
inline const ::std::string& TrackPoint::lontype() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.lonType)
  return *lontype_;
}
inline void TrackPoint::set_lontype(const ::std::string& value) {
  set_has_lontype();
  if (lontype_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lontype_ = new ::std::string;
  }
  lontype_->assign(value);
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.lonType)
}
inline void TrackPoint::set_lontype(const char* value) {
  set_has_lontype();
  if (lontype_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lontype_ = new ::std::string;
  }
  lontype_->assign(value);
  // @@protoc_insertion_point(field_set_char:com.zhichenhaixin.proto.TrackPoint.lonType)
}
inline void TrackPoint::set_lontype(const char* value, size_t size) {
  set_has_lontype();
  if (lontype_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lontype_ = new ::std::string;
  }
  lontype_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.zhichenhaixin.proto.TrackPoint.lonType)
}
inline ::std::string* TrackPoint::mutable_lontype() {
  set_has_lontype();
  if (lontype_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lontype_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:com.zhichenhaixin.proto.TrackPoint.lonType)
  return lontype_;
}
inline ::std::string* TrackPoint::release_lontype() {
  clear_has_lontype();
  if (lontype_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = lontype_;
    lontype_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void TrackPoint::set_allocated_lontype(::std::string* lontype) {
  if (lontype_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete lontype_;
  }
  if (lontype) {
    set_has_lontype();
    lontype_ = lontype;
  } else {
    clear_has_lontype();
    lontype_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:com.zhichenhaixin.proto.TrackPoint.lonType)
}

// optional string latType = 25;
inline bool TrackPoint::has_lattype() const {
  return (_has_bits_[0] & 0x01000000u) != 0;
}
inline void TrackPoint::set_has_lattype() {
  _has_bits_[0] |= 0x01000000u;
}
inline void TrackPoint::clear_has_lattype() {
  _has_bits_[0] &= ~0x01000000u;
}
inline void TrackPoint::clear_lattype() {
  if (lattype_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lattype_->clear();
  }
  clear_has_lattype();
}
inline const ::std::string& TrackPoint::lattype() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.latType)
  return *lattype_;
}
inline void TrackPoint::set_lattype(const ::std::string& value) {
  set_has_lattype();
  if (lattype_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lattype_ = new ::std::string;
  }
  lattype_->assign(value);
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.latType)
}
inline void TrackPoint::set_lattype(const char* value) {
  set_has_lattype();
  if (lattype_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lattype_ = new ::std::string;
  }
  lattype_->assign(value);
  // @@protoc_insertion_point(field_set_char:com.zhichenhaixin.proto.TrackPoint.latType)
}
inline void TrackPoint::set_lattype(const char* value, size_t size) {
  set_has_lattype();
  if (lattype_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lattype_ = new ::std::string;
  }
  lattype_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.zhichenhaixin.proto.TrackPoint.latType)
}
inline ::std::string* TrackPoint::mutable_lattype() {
  set_has_lattype();
  if (lattype_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lattype_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:com.zhichenhaixin.proto.TrackPoint.latType)
  return lattype_;
}
inline ::std::string* TrackPoint::release_lattype() {
  clear_has_lattype();
  if (lattype_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = lattype_;
    lattype_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void TrackPoint::set_allocated_lattype(::std::string* lattype) {
  if (lattype_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete lattype_;
  }
  if (lattype) {
    set_has_lattype();
    lattype_ = lattype;
  } else {
    clear_has_lattype();
    lattype_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:com.zhichenhaixin.proto.TrackPoint.latType)
}

// optional int32 type = 26;
inline bool TrackPoint::has_type() const {
  return (_has_bits_[0] & 0x02000000u) != 0;
}
inline void TrackPoint::set_has_type() {
  _has_bits_[0] |= 0x02000000u;
}
inline void TrackPoint::clear_has_type() {
  _has_bits_[0] &= ~0x02000000u;
}
inline void TrackPoint::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 TrackPoint::type() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.type)
  return type_;
}
inline void TrackPoint::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.type)
}

// optional string aisid = 27;
inline bool TrackPoint::has_aisid() const {
  return (_has_bits_[0] & 0x04000000u) != 0;
}
inline void TrackPoint::set_has_aisid() {
  _has_bits_[0] |= 0x04000000u;
}
inline void TrackPoint::clear_has_aisid() {
  _has_bits_[0] &= ~0x04000000u;
}
inline void TrackPoint::clear_aisid() {
  if (aisid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    aisid_->clear();
  }
  clear_has_aisid();
}
inline const ::std::string& TrackPoint::aisid() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.aisid)
  return *aisid_;
}
inline void TrackPoint::set_aisid(const ::std::string& value) {
  set_has_aisid();
  if (aisid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    aisid_ = new ::std::string;
  }
  aisid_->assign(value);
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.aisid)
}
inline void TrackPoint::set_aisid(const char* value) {
  set_has_aisid();
  if (aisid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    aisid_ = new ::std::string;
  }
  aisid_->assign(value);
  // @@protoc_insertion_point(field_set_char:com.zhichenhaixin.proto.TrackPoint.aisid)
}
inline void TrackPoint::set_aisid(const char* value, size_t size) {
  set_has_aisid();
  if (aisid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    aisid_ = new ::std::string;
  }
  aisid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.zhichenhaixin.proto.TrackPoint.aisid)
}
inline ::std::string* TrackPoint::mutable_aisid() {
  set_has_aisid();
  if (aisid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    aisid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:com.zhichenhaixin.proto.TrackPoint.aisid)
  return aisid_;
}
inline ::std::string* TrackPoint::release_aisid() {
  clear_has_aisid();
  if (aisid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = aisid_;
    aisid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void TrackPoint::set_allocated_aisid(::std::string* aisid) {
  if (aisid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete aisid_;
  }
  if (aisid) {
    set_has_aisid();
    aisid_ = aisid;
  } else {
    clear_has_aisid();
    aisid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:com.zhichenhaixin.proto.TrackPoint.aisid)
}

// optional .com.zhichenhaixin.proto.RadarHistoryTracks tracks = 28;
inline bool TrackPoint::has_tracks() const {
  return (_has_bits_[0] & 0x08000000u) != 0;
}
inline void TrackPoint::set_has_tracks() {
  _has_bits_[0] |= 0x08000000u;
}
inline void TrackPoint::clear_has_tracks() {
  _has_bits_[0] &= ~0x08000000u;
}
inline void TrackPoint::clear_tracks() {
  if (tracks_ != NULL) tracks_->::com::zhichenhaixin::proto::RadarHistoryTracks::Clear();
  clear_has_tracks();
}
inline const ::com::zhichenhaixin::proto::RadarHistoryTracks& TrackPoint::tracks() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.tracks)
  return tracks_ != NULL ? *tracks_ : *default_instance_->tracks_;
}
inline ::com::zhichenhaixin::proto::RadarHistoryTracks* TrackPoint::mutable_tracks() {
  set_has_tracks();
  if (tracks_ == NULL) tracks_ = new ::com::zhichenhaixin::proto::RadarHistoryTracks;
  // @@protoc_insertion_point(field_mutable:com.zhichenhaixin.proto.TrackPoint.tracks)
  return tracks_;
}
inline ::com::zhichenhaixin::proto::RadarHistoryTracks* TrackPoint::release_tracks() {
  clear_has_tracks();
  ::com::zhichenhaixin::proto::RadarHistoryTracks* temp = tracks_;
  tracks_ = NULL;
  return temp;
}
inline void TrackPoint::set_allocated_tracks(::com::zhichenhaixin::proto::RadarHistoryTracks* tracks) {
  delete tracks_;
  tracks_ = tracks;
  if (tracks) {
    set_has_tracks();
  } else {
    clear_has_tracks();
  }
  // @@protoc_insertion_point(field_set_allocated:com.zhichenhaixin.proto.TrackPoint.tracks)
}

// optional int32 diameter = 29;
inline bool TrackPoint::has_diameter() const {
  return (_has_bits_[0] & 0x10000000u) != 0;
}
inline void TrackPoint::set_has_diameter() {
  _has_bits_[0] |= 0x10000000u;
}
inline void TrackPoint::clear_has_diameter() {
  _has_bits_[0] &= ~0x10000000u;
}
inline void TrackPoint::clear_diameter() {
  diameter_ = 0;
  clear_has_diameter();
}
inline ::google::protobuf::int32 TrackPoint::diameter() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.TrackPoint.diameter)
  return diameter_;
}
inline void TrackPoint::set_diameter(::google::protobuf::int32 value) {
  set_has_diameter();
  diameter_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.TrackPoint.diameter)
}

// -------------------------------------------------------------------

// RadarSurfaceTrack

// required int32 flag = 1;
inline bool RadarSurfaceTrack::has_flag() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RadarSurfaceTrack::set_has_flag() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RadarSurfaceTrack::clear_has_flag() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RadarSurfaceTrack::clear_flag() {
  flag_ = 0;
  clear_has_flag();
}
inline ::google::protobuf::int32 RadarSurfaceTrack::flag() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.RadarSurfaceTrack.flag)
  return flag_;
}
inline void RadarSurfaceTrack::set_flag(::google::protobuf::int32 value) {
  set_has_flag();
  flag_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.RadarSurfaceTrack.flag)
}

// required string sourceId = 2;
inline bool RadarSurfaceTrack::has_sourceid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RadarSurfaceTrack::set_has_sourceid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RadarSurfaceTrack::clear_has_sourceid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RadarSurfaceTrack::clear_sourceid() {
  if (sourceid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sourceid_->clear();
  }
  clear_has_sourceid();
}
inline const ::std::string& RadarSurfaceTrack::sourceid() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.RadarSurfaceTrack.sourceId)
  return *sourceid_;
}
inline void RadarSurfaceTrack::set_sourceid(const ::std::string& value) {
  set_has_sourceid();
  if (sourceid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sourceid_ = new ::std::string;
  }
  sourceid_->assign(value);
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.RadarSurfaceTrack.sourceId)
}
inline void RadarSurfaceTrack::set_sourceid(const char* value) {
  set_has_sourceid();
  if (sourceid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sourceid_ = new ::std::string;
  }
  sourceid_->assign(value);
  // @@protoc_insertion_point(field_set_char:com.zhichenhaixin.proto.RadarSurfaceTrack.sourceId)
}
inline void RadarSurfaceTrack::set_sourceid(const char* value, size_t size) {
  set_has_sourceid();
  if (sourceid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sourceid_ = new ::std::string;
  }
  sourceid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.zhichenhaixin.proto.RadarSurfaceTrack.sourceId)
}
inline ::std::string* RadarSurfaceTrack::mutable_sourceid() {
  set_has_sourceid();
  if (sourceid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sourceid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:com.zhichenhaixin.proto.RadarSurfaceTrack.sourceId)
  return sourceid_;
}
inline ::std::string* RadarSurfaceTrack::release_sourceid() {
  clear_has_sourceid();
  if (sourceid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = sourceid_;
    sourceid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RadarSurfaceTrack::set_allocated_sourceid(::std::string* sourceid) {
  if (sourceid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete sourceid_;
  }
  if (sourceid) {
    set_has_sourceid();
    sourceid_ = sourceid;
  } else {
    clear_has_sourceid();
    sourceid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:com.zhichenhaixin.proto.RadarSurfaceTrack.sourceId)
}

// required uint64 UTC = 3;
inline bool RadarSurfaceTrack::has_utc() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RadarSurfaceTrack::set_has_utc() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RadarSurfaceTrack::clear_has_utc() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RadarSurfaceTrack::clear_utc() {
  utc_ = GOOGLE_ULONGLONG(0);
  clear_has_utc();
}
inline ::google::protobuf::uint64 RadarSurfaceTrack::utc() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.RadarSurfaceTrack.UTC)
  return utc_;
}
inline void RadarSurfaceTrack::set_utc(::google::protobuf::uint64 value) {
  set_has_utc();
  utc_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.RadarSurfaceTrack.UTC)
}

// required int32 length = 4;
inline bool RadarSurfaceTrack::has_length() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RadarSurfaceTrack::set_has_length() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RadarSurfaceTrack::clear_has_length() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RadarSurfaceTrack::clear_length() {
  length_ = 0;
  clear_has_length();
}
inline ::google::protobuf::int32 RadarSurfaceTrack::length() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.RadarSurfaceTrack.length)
  return length_;
}
inline void RadarSurfaceTrack::set_length(::google::protobuf::int32 value) {
  set_has_length();
  length_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.RadarSurfaceTrack.length)
}

// repeated .com.zhichenhaixin.proto.TrackPoint trackPoints = 5;
inline int RadarSurfaceTrack::trackpoints_size() const {
  return trackpoints_.size();
}
inline void RadarSurfaceTrack::clear_trackpoints() {
  trackpoints_.Clear();
}
inline const ::com::zhichenhaixin::proto::TrackPoint& RadarSurfaceTrack::trackpoints(int index) const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.RadarSurfaceTrack.trackPoints)
  return trackpoints_.Get(index);
}
inline ::com::zhichenhaixin::proto::TrackPoint* RadarSurfaceTrack::mutable_trackpoints(int index) {
  // @@protoc_insertion_point(field_mutable:com.zhichenhaixin.proto.RadarSurfaceTrack.trackPoints)
  return trackpoints_.Mutable(index);
}
inline ::com::zhichenhaixin::proto::TrackPoint* RadarSurfaceTrack::add_trackpoints() {
  // @@protoc_insertion_point(field_add:com.zhichenhaixin.proto.RadarSurfaceTrack.trackPoints)
  return trackpoints_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::zhichenhaixin::proto::TrackPoint >&
RadarSurfaceTrack::trackpoints() const {
  // @@protoc_insertion_point(field_list:com.zhichenhaixin.proto.RadarSurfaceTrack.trackPoints)
  return trackpoints_;
}
inline ::google::protobuf::RepeatedPtrField< ::com::zhichenhaixin::proto::TrackPoint >*
RadarSurfaceTrack::mutable_trackpoints() {
  // @@protoc_insertion_point(field_mutable_list:com.zhichenhaixin.proto.RadarSurfaceTrack.trackPoints)
  return &trackpoints_;
}

// -------------------------------------------------------------------

// VideoFrame

// required int32 systemAreaCode = 1;
inline bool VideoFrame::has_systemareacode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void VideoFrame::set_has_systemareacode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void VideoFrame::clear_has_systemareacode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void VideoFrame::clear_systemareacode() {
  systemareacode_ = 0;
  clear_has_systemareacode();
}
inline ::google::protobuf::int32 VideoFrame::systemareacode() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.VideoFrame.systemAreaCode)
  return systemareacode_;
}
inline void VideoFrame::set_systemareacode(::google::protobuf::int32 value) {
  set_has_systemareacode();
  systemareacode_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.VideoFrame.systemAreaCode)
}

// required int32 systemIdentificationCode = 2;
inline bool VideoFrame::has_systemidentificationcode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void VideoFrame::set_has_systemidentificationcode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void VideoFrame::clear_has_systemidentificationcode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void VideoFrame::clear_systemidentificationcode() {
  systemidentificationcode_ = 0;
  clear_has_systemidentificationcode();
}
inline ::google::protobuf::int32 VideoFrame::systemidentificationcode() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.VideoFrame.systemIdentificationCode)
  return systemidentificationcode_;
}
inline void VideoFrame::set_systemidentificationcode(::google::protobuf::int32 value) {
  set_has_systemidentificationcode();
  systemidentificationcode_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.VideoFrame.systemIdentificationCode)
}

// required int32 msgIndex = 3;
inline bool VideoFrame::has_msgindex() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void VideoFrame::set_has_msgindex() {
  _has_bits_[0] |= 0x00000004u;
}
inline void VideoFrame::clear_has_msgindex() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void VideoFrame::clear_msgindex() {
  msgindex_ = 0;
  clear_has_msgindex();
}
inline ::google::protobuf::int32 VideoFrame::msgindex() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.VideoFrame.msgIndex)
  return msgindex_;
}
inline void VideoFrame::set_msgindex(::google::protobuf::int32 value) {
  set_has_msgindex();
  msgindex_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.VideoFrame.msgIndex)
}

// required uint32 azimuth = 4;
inline bool VideoFrame::has_azimuth() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void VideoFrame::set_has_azimuth() {
  _has_bits_[0] |= 0x00000008u;
}
inline void VideoFrame::clear_has_azimuth() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void VideoFrame::clear_azimuth() {
  azimuth_ = 0u;
  clear_has_azimuth();
}
inline ::google::protobuf::uint32 VideoFrame::azimuth() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.VideoFrame.azimuth)
  return azimuth_;
}
inline void VideoFrame::set_azimuth(::google::protobuf::uint32 value) {
  set_has_azimuth();
  azimuth_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.VideoFrame.azimuth)
}

// optional uint32 heading = 5;
inline bool VideoFrame::has_heading() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void VideoFrame::set_has_heading() {
  _has_bits_[0] |= 0x00000010u;
}
inline void VideoFrame::clear_has_heading() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void VideoFrame::clear_heading() {
  heading_ = 0u;
  clear_has_heading();
}
inline ::google::protobuf::uint32 VideoFrame::heading() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.VideoFrame.heading)
  return heading_;
}
inline void VideoFrame::set_heading(::google::protobuf::uint32 value) {
  set_has_heading();
  heading_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.VideoFrame.heading)
}

// required double startRange = 6;
inline bool VideoFrame::has_startrange() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void VideoFrame::set_has_startrange() {
  _has_bits_[0] |= 0x00000020u;
}
inline void VideoFrame::clear_has_startrange() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void VideoFrame::clear_startrange() {
  startrange_ = 0;
  clear_has_startrange();
}
inline double VideoFrame::startrange() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.VideoFrame.startRange)
  return startrange_;
}
inline void VideoFrame::set_startrange(double value) {
  set_has_startrange();
  startrange_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.VideoFrame.startRange)
}

// required double rangeFactor = 7;
inline bool VideoFrame::has_rangefactor() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void VideoFrame::set_has_rangefactor() {
  _has_bits_[0] |= 0x00000040u;
}
inline void VideoFrame::clear_has_rangefactor() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void VideoFrame::clear_rangefactor() {
  rangefactor_ = 0;
  clear_has_rangefactor();
}
inline double VideoFrame::rangefactor() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.VideoFrame.rangeFactor)
  return rangefactor_;
}
inline void VideoFrame::set_rangefactor(double value) {
  set_has_rangefactor();
  rangefactor_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.VideoFrame.rangeFactor)
}

// required .com.zhichenhaixin.proto.RES bitResolution = 8;
inline bool VideoFrame::has_bitresolution() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void VideoFrame::set_has_bitresolution() {
  _has_bits_[0] |= 0x00000080u;
}
inline void VideoFrame::clear_has_bitresolution() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void VideoFrame::clear_bitresolution() {
  bitresolution_ = 1;
  clear_has_bitresolution();
}
inline ::com::zhichenhaixin::proto::RES VideoFrame::bitresolution() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.VideoFrame.bitResolution)
  return static_cast< ::com::zhichenhaixin::proto::RES >(bitresolution_);
}
inline void VideoFrame::set_bitresolution(::com::zhichenhaixin::proto::RES value) {
  assert(::com::zhichenhaixin::proto::RES_IsValid(value));
  set_has_bitresolution();
  bitresolution_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.VideoFrame.bitResolution)
}

// required int32 timeOfDay = 9;
inline bool VideoFrame::has_timeofday() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void VideoFrame::set_has_timeofday() {
  _has_bits_[0] |= 0x00000100u;
}
inline void VideoFrame::clear_has_timeofday() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void VideoFrame::clear_timeofday() {
  timeofday_ = 0;
  clear_has_timeofday();
}
inline ::google::protobuf::int32 VideoFrame::timeofday() const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.VideoFrame.timeOfDay)
  return timeofday_;
}
inline void VideoFrame::set_timeofday(::google::protobuf::int32 value) {
  set_has_timeofday();
  timeofday_ = value;
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.VideoFrame.timeOfDay)
}

// repeated int32 amplitude = 10;
inline int VideoFrame::amplitude_size() const {
  return amplitude_.size();
}
inline void VideoFrame::clear_amplitude() {
  amplitude_.Clear();
}
inline ::google::protobuf::int32 VideoFrame::amplitude(int index) const {
  // @@protoc_insertion_point(field_get:com.zhichenhaixin.proto.VideoFrame.amplitude)
  return amplitude_.Get(index);
}
inline void VideoFrame::set_amplitude(int index, ::google::protobuf::int32 value) {
  amplitude_.Set(index, value);
  // @@protoc_insertion_point(field_set:com.zhichenhaixin.proto.VideoFrame.amplitude)
}
inline void VideoFrame::add_amplitude(::google::protobuf::int32 value) {
  amplitude_.Add(value);
  // @@protoc_insertion_point(field_add:com.zhichenhaixin.proto.VideoFrame.amplitude)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
VideoFrame::amplitude() const {
  // @@protoc_insertion_point(field_list:com.zhichenhaixin.proto.VideoFrame.amplitude)
  return amplitude_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
VideoFrame::mutable_amplitude() {
  // @@protoc_insertion_point(field_mutable_list:com.zhichenhaixin.proto.VideoFrame.amplitude)
  return &amplitude_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace zhichenhaixin
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::com::zhichenhaixin::proto::MSGTYP> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::com::zhichenhaixin::proto::MSGTYP>() {
  return ::com::zhichenhaixin::proto::MSGTYP_descriptor();
}
template <> struct is_proto_enum< ::com::zhichenhaixin::proto::CNF> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::com::zhichenhaixin::proto::CNF>() {
  return ::com::zhichenhaixin::proto::CNF_descriptor();
}
template <> struct is_proto_enum< ::com::zhichenhaixin::proto::CST> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::com::zhichenhaixin::proto::CST>() {
  return ::com::zhichenhaixin::proto::CST_descriptor();
}
template <> struct is_proto_enum< ::com::zhichenhaixin::proto::STH> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::com::zhichenhaixin::proto::STH>() {
  return ::com::zhichenhaixin::proto::STH_descriptor();
}
template <> struct is_proto_enum< ::com::zhichenhaixin::proto::RES> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::com::zhichenhaixin::proto::RES>() {
  return ::com::zhichenhaixin::proto::RES_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ZCHXRadar_2eproto__INCLUDED
